# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 344d1d4a3362c00ed3d467ff44a4da632bda20e87aecd4023828e2d20c3ef7d04f1f1100ea41d2f5a9c8df04464721eb1463bc32c2803c260dccc222c22ee843

test:
  secret_key_base: c965df35809a27cd2b775f29ab86461ba2442b755527a756388e1cce7c651428182b65981befc8131aa9d911650ef1a42ade16cc859165e169b1d1c8e23dadff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
